### ISSUE TITLE
Can't unjail validator

### ISSUE THREAD

**Issue by quangtuyen88** [allora-network/allora-chain#358]
```
 allorad --home=$APP_HOME tx slashing unjail   --chain-id testnet   --node https://allora-testnet-rpc.polkachu.com:443    --from dragon   --keyring-backend=test
Error: dragon.info: key not found
dragon.info: key not found [cosmos/cosmos-sdk@v0.50.3/crypto/keyring/keyring.go:538]
root@33f65a8c54f2:/data# allorad --home=$APP_HOME tx slashing unjail \
  --chain-id testnet \
  --from dragon \
  --keyring-backend=test \
  --node https://allora-testnet-rpc.polkachu.com:443
Error: dragon.info: key not found
dragon.info: key not found [cosmos/cosmos-sdk@v0.50.3/crypto/keyring/keyring.go:538]
```
I can see my key here :
```
allorad --home=$APP_HOME keys list --keyring-backend test
- address: allo14xa9l84h75zychu8sj93wtjd46g56qp8e8v68f
  name: dragon
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"An/B8RU1O5es/egLKwuouITAwGrp8uJrePIOJYHcsV6A"}'
  type: local
```

I can query balance : 
```
  allorad --home=$APP_HOME q bank balances $(allorad --home=$APP_HOME keys show dragon -a --keyring-backend=test)
balances:
- amount: "1000000000"
  denom: uallo
pagination:
  total: "1"
```
